In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use("ggplot")

In [ ]:
df = pd.read_csv("/content/Advanced E-Commerce Dataset for SQL Python or Power BI Projects.csv")

df.head()

,Order_ID,Order_Date,Region,Product_Category,Marketing_Spend,Website_Visits,Orders,Revenue,Return_Rate,Delivery_Days,Customer_Rating,Payment_Mode,Discount_Percent,Shipping_Cost,Customer_Segment,Repeat_Customer
0,ORD10001,14-01-2025,West,Shoes,6091,8764,394,739932,14.0,7,3.2,Net Banking,17,217,Regular,No
1,ORD10002,29-03-2025,North,Watches,3881,16190,265,857805,2.7,2,4.6,UPI,12,121,Regular,Yes
2,ORD10003,23-01-2025,East,Shoes,3792,18993,294,590352,7.5,1,4.3,UPI,33,91,Budget,Yes
3,ORD10004,06-02-2025,South,Shoes,8732,14055,326,904976,11.1,6,2.6,UPI,13,200,Regular,No
4,ORD10005,29-03-2025,East,Watches,2551,13524,408,1377000,3.7,3,4.9,Debit Card,25,211,Budget,Yes

In [ ]:
df.tail()

,Order_ID,Order_Date,Region,Product_Category,Marketing_Spend,Website_Visits,Orders,Revenue,Return_Rate,Delivery_Days,Customer_Rating,Payment_Mode,Discount_Percent,Shipping_Cost,Customer_Segment,Repeat_Customer
9995,ORD19996,09-06-2025,East,Bags,3589,17110,276,922392,6.1,4,4.8,Net Banking,35,166,Budget,Yes
9996,ORD19997,10-06-2025,North,Bags,3148,10086,327,655635,5.7,2,4.6,UPI,19,155,Regular,Yes
9997,ORD19998,17-04-2025,North,Clothing,5367,15237,267,587400,3.6,2,4.8,Net Banking,26,179,Regular,Yes
9998,ORD19999,05-06-2025,West,Electronics,6606,18946,400,1125600,9.2,7,3.5,Credit Card,27,136,Premium,No
9999,ORD20000,20-06-2025,West,Watches,5102,18872,135,219375,15.7,8,4.0,Debit Card,23,198,Premium,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  object
 1   Order_Date        10000 non-null  object
 2   Region            10000 non-null  object
 3   Product_Category  10000 non-null  object
 4   Marketing_Spend   10000 non-null  int64
 5   Website_Visits    10000 non-null  int64
 6   Orders            10000 non-null  int64
 7   Revenue           10000 non-null  int64
 8   Return_Rate       10000 non-null  float64
 9   Delivery_Days     10000 non-null  int64
 10  Customer_Rating   10000 non-null  float64
 11  Payment_Mode      10000 non-null  object
 12  Discount_Percent  10000 non-null  int64
 13  Shipping_Cost     10000 non-null  int64
 14  Customer_Segment  10000 non-null  object
 15  Repeat_Customer   10000 non-null  object
dtypes: float64(2), int64(7), object(7)
memory usage: 1.2+ MB

In [ ]:
df.describe()

,Marketing_Spend,Website_Visits,Orders,Revenue,Return_Rate,Delivery_Days,Customer_Rating,Discount_Percent,Shipping_Cost
count,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5625.150900,13534.888100,292.332800,7.684876e+05,8.627380,4.218900,4.057360,20.10210,165.111600
std,1763.301187,3746.480652,74.418431,2.547943e+05,4.127491,2.178361,0.569096,8.97729,49.551207
min,2501.000000,7000.000000,120.000000,1.872060e+05,1.000000,1.000000,2.100000,5.00000,80.000000
25%,4224.000000,10334.750000,228.000000,5.807152e+05,5.000000,2.000000,3.600000,12.00000,122.000000
50%,5542.000000,13518.000000,291.000000,7.472835e+05,7.900000,4.000000,4.100000,20.00000,165.000000
75%,7006.250000,16790.000000,358.000000,9.456300e+05,12.200000,6.000000,4.500000,28.00000,208.000000
max,9000.000000,19999.000000,420.000000,1.465662e+06,21.900000,8.000000,5.000000,35.00000,250.000000

In [ ]:
df.shape

(10000, 16)

In [ ]:
df.columns

Index(['Order_ID', 'Order_Date', 'Region', 'Product_Category',
       'Marketing_Spend', 'Website_Visits', 'Orders', 'Revenue', 'Return_Rate',
       'Delivery_Days', 'Customer_Rating', 'Payment_Mode', 'Discount_Percent',
       'Shipping_Cost', 'Customer_Segment', 'Repeat_Customer'],
      dtype='object')

In [ ]:
# Missing values
df.isnull().sum()

Order_ID            0
Order_Date          0
Region              0
Product_Category    0
Marketing_Spend     0
Website_Visits      0
Orders              0
Revenue             0
Return_Rate         0
Delivery_Days       0
Customer_Rating     0
Payment_Mode        0
Discount_Percent    0
Shipping_Cost       0
Customer_Segment    0
Repeat_Customer     0
dtype: int64

In [ ]:
#Remove duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# Convert Date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

/tmp/ipykernel_4441/4007527700.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [ ]:
print(df["Website_Visits"].sum())

135348881

In [ ]:
print(df["Orders"].sum())

2923328

In [ ]:
print(df["Revenue"].sum())

7684875505

In [ ]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Region', 'Product_Category',
       'Marketing_Spend', 'Website_Visits', 'Orders', 'Revenue', 'Return_Rate',
       'Delivery_Days', 'Customer_Rating', 'Payment_Mode', 'Discount_Percent',
       'Shipping_Cost', 'Customer_Segment', 'Repeat_Customer'],
      dtype='object')

In [ ]:
# Data cleaning
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

In [ ]:
df.to_csv("cleaned_ecommerce_data.csv", index=False)

In [ ]:
from google.colab import files

files.download("cleaned_ecommerce_data.csv")